// This file is generated by Velite

import config from '../velite.config'

type Collections = typeof config.collections

export type Other = Collections['other']['schema']['_output']
export declare const other: Other[]

export type Post = Collections['posts']['schema']['_output']
export declare const posts: Post[]
